name: Update GitHub Stats

on:
  schedule:
    # Corre cada 12 horas
    - cron: '0 */12 * * *'
  workflow_dispatch: # Permite ejecuci√≥n manual
  push:
    branches:
      - main

jobs:
  update-readme:
    name: Update README with GitHub stats
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub stats
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          COMMIT_MSG: 'Update GitHub stats'
          MAX_LINES: 10
